/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutTimeTrackingRouteImport } from './routes/_layout/time-tracking'
import { Route as LayoutTimeOffRouteImport } from './routes/_layout/time-off'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPeopleRouteImport } from './routes/_layout/people'
import { Route as LayoutDocumentsRouteImport } from './routes/_layout/documents'
import { Route as LayoutManagerIndexRouteImport } from './routes/_layout/manager/index'
import { Route as LayoutApprovalsIndexRouteImport } from './routes/_layout/approvals/index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTimeTrackingRoute = LayoutTimeTrackingRouteImport.update({
  id: '/time-tracking',
  path: '/time-tracking',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTimeOffRoute = LayoutTimeOffRouteImport.update({
  id: '/time-off',
  path: '/time-off',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPeopleRoute = LayoutPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocumentsRoute = LayoutDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutManagerIndexRoute = LayoutManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApprovalsIndexRoute = LayoutApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents': typeof LayoutDocumentsRoute
  '/people': typeof LayoutPeopleRoute
  '/settings': typeof LayoutSettingsRoute
  '/time-off': typeof LayoutTimeOffRoute
  '/time-tracking': typeof LayoutTimeTrackingRoute
  '/approvals/': typeof LayoutApprovalsIndexRoute
  '/manager/': typeof LayoutManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documents': typeof LayoutDocumentsRoute
  '/people': typeof LayoutPeopleRoute
  '/settings': typeof LayoutSettingsRoute
  '/time-off': typeof LayoutTimeOffRoute
  '/time-tracking': typeof LayoutTimeTrackingRoute
  '/approvals': typeof LayoutApprovalsIndexRoute
  '/manager': typeof LayoutManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/documents': typeof LayoutDocumentsRoute
  '/_layout/people': typeof LayoutPeopleRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/time-off': typeof LayoutTimeOffRoute
  '/_layout/time-tracking': typeof LayoutTimeTrackingRoute
  '/_layout/approvals/': typeof LayoutApprovalsIndexRoute
  '/_layout/manager/': typeof LayoutManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documents'
    | '/people'
    | '/settings'
    | '/time-off'
    | '/time-tracking'
    | '/approvals/'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documents'
    | '/people'
    | '/settings'
    | '/time-off'
    | '/time-tracking'
    | '/approvals'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/documents'
    | '/_layout/people'
    | '/_layout/settings'
    | '/_layout/time-off'
    | '/_layout/time-tracking'
    | '/_layout/approvals/'
    | '/_layout/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/time-tracking': {
      id: '/_layout/time-tracking'
      path: '/time-tracking'
      fullPath: '/time-tracking'
      preLoaderRoute: typeof LayoutTimeTrackingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/time-off': {
      id: '/_layout/time-off'
      path: '/time-off'
      fullPath: '/time-off'
      preLoaderRoute: typeof LayoutTimeOffRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/people': {
      id: '/_layout/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof LayoutPeopleRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/documents': {
      id: '/_layout/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof LayoutDocumentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/manager/': {
      id: '/_layout/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof LayoutManagerIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/approvals/': {
      id: '/_layout/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof LayoutApprovalsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutDocumentsRoute: typeof LayoutDocumentsRoute
  LayoutPeopleRoute: typeof LayoutPeopleRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTimeOffRoute: typeof LayoutTimeOffRoute
  LayoutTimeTrackingRoute: typeof LayoutTimeTrackingRoute
  LayoutApprovalsIndexRoute: typeof LayoutApprovalsIndexRoute
  LayoutManagerIndexRoute: typeof LayoutManagerIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDocumentsRoute: LayoutDocumentsRoute,
  LayoutPeopleRoute: LayoutPeopleRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTimeOffRoute: LayoutTimeOffRoute,
  LayoutTimeTrackingRoute: LayoutTimeTrackingRoute,
  LayoutApprovalsIndexRoute: LayoutApprovalsIndexRoute,
  LayoutManagerIndexRoute: LayoutManagerIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
